package(                                                                                            
  default_visibility = ["//docker"]                                                                   
)
