load("@rules_python//python:defs.bzl", "py_binary", "py_library")                                   
                                                                                                    
py_binary(                                                                                          
  name = "train",                                                                                   
  srcs = ["train.py"],                                                                              
)                                                                                                   
                                                                                                    
py_binary(                                                                                          
  name = "mnist",                                                                                   
  srcs = ["mnist.py"],                                                                              
)                                                                                                   
